### ISSUE TITLE
xsens status while using ntrip and rtk signal is not changing to RTK fix

### ISSUE THREAD

**Issue by MortezaAliyari** [jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client#3]
Hi there,
I was using the ros1 ```(https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client)``` package and by using the proper username and password, I was receiving an RTK signal both in FIX and Floating type during navigation. I was using Ubuntu 18 and ros1 melodic. But after migrating to the ROS2 humble version,changing the OS to Ubuntu 22.04 and using ```(https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client)``` driver from the ros2 branch, RTK fix situation rarely happened. I always check the ```xsens_status```topic from the driver which most of the time changes from 0 to 1. so rarely type two (RTK FIX) is observed.
However, by using the same hardware and device and only switching to ros1 I'm receiving an RTK fix signal.
**Is there any idea why RTK type 2 rarely happening?**
Thanks

**Comment by jiminghe** [comment]
Hi,
I think the problem might be that you need to select the PvtData in the Output Configuration, I had updated the Output Configuration image of ROS2 to the same one with ROS1.
Let me know if it works.

**Comment by MortezaAliyari** [comment]
@jiminghe thanks for your reply.
PvtData was checked. For a while, I'm recieving RTK FIX information and then I don't have it at all, or at least Mti 680G is not receiving it. Now i have another question!
Without using the driver how can check whether device receives the RTK FIX information or not.
 As I said I don't have this issue with ros1 driver, however they are connected to the same network and hardware!

**Comment by jiminghe** [comment]
![statusplot_2024-04-10_18h49_MTi-680G-8A1G6_0080001CDB_GeneralMag_RTK_full](https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client/assets/89671976/626fb2ba-4645-442d-8255-43d88c87276f)

Hi,
I updated the ROS2 Driver's ntrip_util.cpp ad nmeapublisher.h to handle only the pvtdata and corrected the fixtype, previously the fixtype was using the Xsens PvtData fixtype, which is different than the NMEA GPGGA fixtype.
I tested for 6min, and I could get RTK Float 16 seconds after the GNSS Fix, then after about 8 seconds, I could get RTK Fix, and the RTK Fix continues for the whole testing process(of course, the antenna was installed on the top of the car, with a clear sky view).

Please help to test at your end, to see if it works, thanks!

**Comment by MortezaAliyari** [comment]
@jiminghe 
I tried again with your new changes and still is the same as before.
![Screenshot from 2024-04-15 13-03-28](https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client/assets/79801785/7a83fede-16c4-438a-bc17-fd2e74efa94b)

**Comment by MortezaAliyari** [comment]
@jiminghe  
I want to upgrade the Xsens firmware. I tried the last version of the firmware uploader software and one before the last one on win10. I couldn't upload the downloaded firmware, because it couldn't find the device! I checked the device manager USB part, mti convert is over there!
i can find the devices through Linux ```mtmanager``` software and change the baudrate and config.
I don't know why "firmware uploader " is not working. 
what should I do? 
regrads

**Comment by AOEknabos** [comment]
I am using ROS1 and have followed instructions from the readme, while using MTi-680G. I have the following questions to ask.

1. I am having RTK status fluctuating between 1 and 2, an in some other instances 0. With rarely a stable value of 2 in a good network environment. I have Pvt Data set to true within the yaml file as i am not using the MT manager.
How can i get stable RTK

2. Is there a need to clear and rebuild completely the catkin workspace anytime i change parameters within the xsens_mti_node.yaml file?

3. I am getting the below warning anytime i run:
"roslaunch xsens_mti_driver xsens_mti_node.launch"

"[ WARN] [1717598740.055066905]: Rosnode time_option is using host controller's ros time, no recommended, use MT Manager - Device Settings - Output Configurations to select utc time or sample time fine, and set time_option to 0 or 1 in the xsens_mti_node.yaml file."

I am in addition to the ROS driver, running a script which uses my PC clock to record videos and i am cautious of time drift. I had set the time option to 2 to use my device clock. 

4. I am a bit confused about how to set PVtData to true away from the MT manager as it is not within xsen_mti_node.yaml

**Comment by AOEknabos** [comment]
![image](https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client/assets/130047500/1e7ced48-43f7-46ad-b993-d461fffa9a2f)


I am having firmware warnings too. COuld it be causing my issues?

**Comment by MortezaAliyari** [comment]
@AOEknabos 
About your questions:
2. No need to rebuild the workspace
3. connect your device to Mtmanager and choose utc_time. if you have trouble to find the device check the boudrate.
4. You should use Mtmanager software to check this option.
But i also have same issue as you mentioned in Q1. it seems the solution relate to firmware and it need to be updated!
I have win10 and the new and old version(4.3) of firmware uploader is not working properly. so i can't update my firmware. 
I don't know if anyone else has this issue with firmware uploader.

**Comment by MortezaAliyari** [comment]
The problem is solved by upgrading the firmware of the device.
The case is closed
