### ISSUE TITLE
Role of this Repository?

### ISSUE THREAD

**Issue by ebnerluca** [jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client#4]
Hey there,

although this is not an issue regarding the functionality of the code itself, I wanted to clarify the role/purpose of this repository.

So far I was using the ros driver which came with the downloadable MT SDK through this link:
https://www.movella.com/support/software-documentation

Even when looking into the newest beta version 2024.1, it seems to be outdated compared to the version on this repo here.
How does the development process of these MT SDK versions and this repo here relate?
I really like the added functionality of this repository, especially the configuration capabilities and NTRIP client! Ideally I would like to merge future updates with my own customizations, this is the reason why I'm asking.

Cheers

**Comment by jiminghe** [comment]
Hi,
The xspublic of this repo is aligned with the xspublic in the MT SDK, but the ROS driver in there is indeed very old(no update for about 6 years). 
The role of this Repo is to update constantly and add new features for the Xsens MTi ROS Driver, and feel free to add more comments and suggestions.
Hope in the near future would be able to merge to the Xsens MT Software Suite.

**Comment by ebnerluca** [comment]
Thanks for the fast reply, I will switch to this newer version then.
It would be helpful to state somewhere the relation between this repo and the MT SDK, so other people can see it too.

I appreciate the updates!
