### ISSUE TITLE
Bug: Impossible to disable inrun compass calibration

### ISSUE THREAD

**Issue by ebnerluca** [jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client#5]
https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client/blob/ab0031c63783e83d4b0dc458ef04c4177149945b/src/xsens_ros_mti_driver/src/xdainterface.cpp#L892C5-L902C6

^ Unreachable code. If `enable_inrun_compass_calibration` is false, then the whole section is skipped and inrun compass calibration does not get disabled.
The same issue is present in other flags as well, e.g. `enable_active_heading_stabilization` and others.

**Comment by ebnerluca** [comment]
PR #6 should fix this. 
Tested for AHS and Inrun compass calibration flags, untested for the others.

**Comment by jiminghe** [comment]
Thank! merged to the main.
