### ISSUE TITLE
Ros Topic: No new messages

### ISSUE THREAD

**Issue by skepsl** [jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client#7]
Hallo, thank you for providing the code for me to try.

I use the code to test my IMU xsens MTi-100, using ROS Noetic with ubuntu 20.04. 
Actually I tested the IMU using the mtmanager, and it works well.
However, I have a problem when I try using ROS. so after building my WS, I run the roslaunch with display.
I change the fixed frame in rviz into imu_link as noted. However, I could not get the data from the ros topic.
when I echo the data from /imu/data, it says that the is no new messages, also when I run rostopic hz imu/data, it appears to be no data in the topic.

Hv you perhap ever encountered the same problem as me.? did I miss something during my setup?

Any help is really be appreciated
Thank you,

**Comment by jiminghe** [comment]
Hi,

You could firstly check your output configuration in MT Manager - Device Settings - Output Configuration, to make sure you have selected the RateOfTurn, Acceleration, then in the /imu/data, you should have the output, but you won't have the orientation(MTi-100 doesn't have orientation output).

**Comment by skepsl** [comment]
Hello, Thank you for quick response.
It works on my PC of x86 architecture,
but when I move the sensor into my robot, which has  Nvidia Jetson Orin (ARM architecture), it shows "WARNING: topic [/imu/data] does not appear to be published yet", but I cannot open the mtmanager as it was on my PC. 
how should I address these issues ? thank you

**Comment by jiminghe** [comment]
For the Jetson Orin, you need to change the [xsens_mti_node.yaml](https://github.com/jiminghe/Xsens_MTi_ROS_Driver_and_Ntrip_Client/blob/main/src/xsens_ros_mti_driver/param/xsens_mti_node.yaml):
```
scan_for_devices: false
port: '/dev/ttyUSB0' # Uncomment and set your device's port.
baudrate: 115200     # Uncomment and set your device's baudrate.
```
If you had done the above steps, you could also use the Cutecom to check if you could receive the hex bytes: `FA FF 36 ...`:
```
sudo apt install cutecom
```
then in the terminal run:
```
cutecom
```
Then click the settings to choose the right port and baudrate, click open, please check if you could receive the hex messages `FA FF 36...` from there.
